// Auth constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const RESET_LOGIN_STATE = 'RESET_LOGIN_STATE'

// Fetch Resturant list
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE'
export const RESET_LIST_STATE = 'RESET_LIST_STATE'

// Fetch Resturant list
export const FETCH_RESTAURENTS_REQUEST = 'FETCH_RESTAURENTS_REQUEST'
export const FETCH_RESTAURENTS_SUCCESS = 'FETCH_RESTAURENTS_SUCCESS'
export const FETCH_RESTAURENTS_FAILURE = 'FETCH_RESTAURENTS_FAILURE'
export const RESET_RESTAURENTS_STATE = 'RESET_RESTAURENTS_STATE'