export const resturants = [
    {
        id: 101,
        name: "McDonal's",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/mcdonal.jpg'),
        distance: 1,
        charges: '25$',
        rating: 4.4,

    },
    {
        id: 102,
        name: "Subway",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/subway.jpg'),
        distance: 0.5,
        charges: '20$',
        rating: 4.4,

    },
    {
        id: 103,
        name: "McDonal's",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/mcdonal.jpg'),
        distance: 0.4,
        charges: '10$',
        rating: 4.4,

    },
    {
        id: 104,
        name: "Subway",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/subway.jpg'),
        distance: 0.3,
        charges: '15$',
        rating: 4.4,
    },
    {
        id: 105,
        name: "McDonal's",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/mcdonal.jpg'),
        distance: 0.2,
        charges: '10$',
        rating: 4.4,
    },
    {
        id: 106,
        name: "Subway",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/subway.jpg'),
        distance: 0.7,
        charges: '25$',
        rating: 4.4,
    },
    {
        id: 107,
        name: "McDonal's",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/mcdonal.jpg'),
        distance: 0.8,
        charges: '20$',
        rating: 4.4,
    },
    {
        id: 108,
        name: "Subway",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        image: require('../assets/images/subway.jpg'),
        distance: 0.9,
        charges: '15$',
        rating: 4.4,
    }
]